# Generated by Django 5.2.3 on 2025-06-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='marks_obtained',
            new_name='marks',
        ),
    ]
